{% set name = "ravenpy" %}
{% set version = "0.14.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2ff324a73a2aa2be7bad7c4c200f0aab201d1e145220dd47f838aaf91983b9ca

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  script_env:
    - CONDA_BUILD

requirements:
  host:
    - python >=3.9
    - flit
    - pip
  run:
    - python >=3.9
    - raven-hydro >=0.2.4,<1.0
    - affine
    - cf_xarray
    - cftime
    - click >=8.0.0
    - climpred >=2.4.0
    - dask
    - fiona >=1.9
    - gdal >=3.0
    - geopandas >=0.13.0
    - h5netcdf
    - haversine
    - lxml
    - matplotlib-base
    - netcdf4
    - numpy
    - owslib >=0.24.1,<0.29  # see: https://github.com/geopython/OWSLib/issues/871
    - pandas >=2.2.0
    - pint >=0.20
    - platformdirs
    - pydantic >=2.0
    - pymbolic
    - pyogrio
    - pyproj >=3.0.0
    - rasterio
    - requests
    - rioxarray
    - scipy
    - shapely
    - spotpy
    - statsmodels
    - typing_extensions
    - xarray >=2023.11.0
    - xclim >=0.48.2
    - xskillscore

test:
  requires:
    - pip
  imports:
    - ravenpy
  commands:
    - raven -v
    - pip check

about:
  home: https://github.com/CSHS-CWRA/RavenPy
  dev_url: https://github.com/CSHS-CWRA/RavenPy
  doc_url: https://ravenpy.readthedocs.io/en/latest/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Python package to help run Raven, the hydrologic modelling framework.

extra:
  recipe-maintainers:
    - Zeitsperre
    - huard
    - cjauvin
