{% set name = "ravenpy" %}
{% set version = "0.16.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c095e4dda876a8718a0c255b80cc68cdf7e4e754c5cc2a6d8b534dcf27578b30

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  script_env:
    - CONDA_BUILD

requirements:
  host:
    - python >=3.9
    - flit
    - pip
  run:
    - python >=3.9
    - raven-hydro >=0.3.1,<1.0
    - affine
    - cf_xarray
    - cftime
    - click >=8.0.0
    - climpred >=2.4.0
    - dask
    - fiona >=1.9
    - gdal >=3.1
    - geopandas >=0.14.0
    - h5netcdf
    - haversine
    - lxml
    - matplotlib-base
    - netcdf4 <=1.6.5
    - numpy <2.0.0
    - owslib >=0.29.1
    - pandas >=2.2.0
    - pint >=0.20,<0.24
    - platformdirs
    - pydantic >=2.0
    - pydap
    - pymbolic
    - pyogrio <0.8.0
    - pyproj >=3.0.0
    - rasterio
    - requests
    - rioxarray
    - scipy
    - shapely
    - spotpy
    - statsmodels
    - typing_extensions
    - xarray >=2023.11.0
    - xclim >=0.50.0
    - xskillscore

test:
  requires:
    - pip
  imports:
    - ravenpy
  commands:
    - raven -v
    - pip check

about:
  home: https://github.com/CSHS-CWRA/RavenPy
  dev_url: https://github.com/CSHS-CWRA/RavenPy
  doc_url: https://ravenpy.readthedocs.io/en/latest/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Python package to help run Raven, the hydrologic modelling framework.

extra:
  recipe-maintainers:
    - Zeitsperre
    - huard
    - cjauvin
