{% set name = "ravenpy" %}
{% set version = "0.7.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3565a425fdae271ee539fb072f8085f8d75182e1b96fa12864afe18ac0ef9e61

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - setuptools
    - numpy >=1.20
    - gdal
    - pip
  run:
    - raven-hydro ==3.0.4.322
    - ostrich ==21.03.16
    - python >=3.7
    - cftime
    - cf_xarray
    - click >7
    - climpred >=2.1.6
    - dask
    - fiona
    - gdal
    - geopandas >=0.9
    - haversine
    - netcdf4
    - lxml
    - matplotlib-base
    - numpy
    - owslib
    - pandas
    - pydantic
    - pyproj >=3
    - rasterio <=1.2.6
    - requests
    - rioxarray
    - scipy >=1.6.3
    - shapely
    - statsmodels
    - xarray >=0.18
    - xclim >=0.29.0

test:
  imports:
    - ravenpy
  commands:
    - raven -v
    - ostrich

about:
  home: https://github.com/CSHS-CWRA/RavenPy
  dev_url: https://github.com/CSHS-CWRA/RavenPy
  doc_url: https://ravenpy.readthedocs.io/en/latest/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Python wrapper to setup and run the hydrologic modelling framework Raven.

extra:
  recipe-maintainers:
    - Zeitsperre
    - cjauvin
