{% set name = "ravenpy" %}
{% set version = "0.16.1" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 67a94d7a67f372a50d36acffc12424af71a16890b298677722dc7a015b2c304c

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  script_env:
    - CONDA_BUILD

requirements:
  host:
    - python {{ python_min }}
    - flit-core >=3.9,<4.0
    - pip
  run:
    - python >={{ python_min }}
    - raven-hydro >=0.3.1,<1.0
    - affine >=2.4.0
    - cf_xarray >=0.9.3
    - cftime
    - click >=8.0.0
    - climpred >=2.4.0
    - dask >=2024.4.0
    - fiona >=1.9
    - gdal >=3.1
    - geopandas >=1.0
    - h5netcdf >=1.3.0
    - haversine >=2.8.0
    - lxml
    - matplotlib-base >=3.6.0
    - netcdf4 <=1.6.5
    - numpy >=1.23,<2.0.0
    - owslib >=0.29.1
    - pandas >=2.2.0
    - pint >=0.20,<0.24
    - platformdirs
    - pydantic >=2.0
    - pydap >=3.4.0
    - pymbolic >=2024.2
    - pyogrio <0.8.0
    - pyproj >=3.3.0
    - rasterio
    - rioxarray
    - scipy >=1.9.0
    - shapely >=2.0
    - spotpy >=1.6.1
    - statsmodels >=0.14.2
    - typing_extensions
    - xarray >=2023.11.0
    - xclim >=0.50.0
    - xskillscore

test:
  requires:
    - pip
    - python {{ python_min }}
  imports:
    - ravenpy
  commands:
    - raven -v
    - pip check | true

about:
  home: https://github.com/CSHS-CWRA/RavenPy
  dev_url: https://github.com/CSHS-CWRA/RavenPy
  doc_url: https://ravenpy.readthedocs.io/en/latest/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Python package to help run Raven, the hydrologic modelling framework.

extra:
  recipe-maintainers:
    - Zeitsperre
    - huard
    - cjauvin
