{% set name = "ravenpy" %}
{% set version = "0.21.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b3677b102311b6371d76de09d262a2a3843d2760c5b89ee3650fbbc9c30f4d1b

build:
  noarch: python
  number: 2
  script: {{ PYTHON }} -m pip install . -vv
  script_env:
    - CONDA_BUILD

requirements:
  host:
    - python {{ python_min }}
    - flit-core >=3.11.0,<4.0
    - pip >=26.0.1
  run:
    - python >={{ python_min }}
    - affine >=2.4.0
    - cf_xarray >=0.9.3
    - cftime >=1.4.1
    - click >=8.3.1
    - climpred >=2.6.0
    - filelock >=3.14.0
    - fiona >=1.9
    - gdal >=3.1
    - geopandas >=1.0
    - h5netcdf >=1.5.0
    - haversine >=2.8.0
    - lxml
    - matplotlib-base >=3.6.0
    - netcdf4
    - numpy >=1.25.0
    - owslib >=0.29.1
    - packaging
    - pandas >=2.2.0
    - pint >=0.24.4
    - pydantic >=2.11
    - pymbolic >=2024.2
    - pyproj >=3.3.0
    - rasterio
    - requests >=2.32.2
    - rioxarray
    - scipy >=1.11.0
    - shapely >=2.0
    - spotpy >=1.6.1
    - statsmodels >=0.14.2
    - xarray >=2023.11.0,!=2024.10.0
    - xclim >=0.57.0
  run_constrained:
    - raven-hydro >=4.12.1,<5.0

test:
  requires:
    - pip >=26.0.1
    - pooch >=1.8.0
    - pytest >=9.0.2
    - pytest-xdist >=3.2.0
    - python {{ python_min }}
    - raven-hydro >=4.12.1,<5.0
  source_files:
    - pyproject.toml
    - src/ravenpy
    - tests
  imports:
    - ravenpy
  commands:
    - raven -v
    - pip check || true  # issue with version string for spotpy
    - pytest -m "not online" -k "not test_raster_warp and not test_warped_raster_aspect"  # issue with precision

about:
  home: https://github.com/CSHS-CWRA/RavenPy
  dev_url: https://github.com/CSHS-CWRA/RavenPy
  doc_url: https://ravenpy.readthedocs.io/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Python wrapper for configuring and running the hydrologic modelling framework Raven.
  description: |
    RavenPy is a Python wrapper for Raven, accompanied by utility functions that
    facilitate model configuration, calibration, and evaluation.

extra:
  recipe-maintainers:
    - Zeitsperre
    - huard
    - cjauvin
